### ISSUE TITLE
Needs for the Arduino Example to work...

### ISSUE THREAD

**Issue by Leamucho** [bakercp/ofxOscSerial#1]
Hello, I wanted first to thank for your work, this is what I was trying to begin to develop, and I didnt know if I was going to get it done hehehe...

anyway, th issue, is that for the example []((https://github.com/bakercp/ofxOscSerial/tree/master/example/Arduino) to work, we also need your BufferUtils, so, it is so small the issue, I think I can fork it, but wanted to drop you a line.

good day

**Comment by bakercp** [comment]
Fixed with #2 Thanks @Leamucho
